main/urls.py
from django.urls import path,include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('educations', views.educations, name='educations'),
    path('experiences', views.experiences, name='experiences'),
    path('project', views.project, name='project'),
    path('story1', views.story1, name='story1'),
    path('contact', views.contact, name='contact'),
    path('story5/', include('story5.urls',namespace='story5')),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story5.urls')),
]

story5/urls.py
from django.urls import path

from . import views
from .views import courses,addcourse,detailcourse,deletecourse

app_name = 'story5'

urlpatterns = [
    path('', courses.as_view(), name='courses'),
    path('addcourse', views.addcourse, name='addcourse'),
    path('detailcourse/<pk>/',detailcourse.as_view(),name='detailcourse'),
    path('deletecourse/(?P<delete_id>[0-9])',views.deletecourse,name='deletecourse')
]

main/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
Credit_Choices=[
    ('one','1'),
    ('two','2'),
    ('three','3'),
    ('four','4'),
    ('five','5'),
    ('six','6'),
    ('seven','7')
]

Semester_Choices=[
    ('Gasal','Gasal 2020/2021')
]
class PostCourse(models.Model):
    Course = models.CharField(max_length=20)
    Lecturer = models.CharField(max_length=20)
    Credit = models.CharField(max_length=20, choices=Credit_Choices,default='1')
    Semester = models.CharField(max_length=20, choices=Semester_Choices,default='Gasal 2020/2021')
    Description = models.TextField()

    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.Course
    
 

story5/forms.py
from django.forms import ModelForm
from django import forms
from .models import PostCourse

class CourseForm(forms.ModelForm):
    class Meta:
        model = PostCourse
        fields = [
            'Course',
            'Lecturer',
            'Credit',
            'Semester',
            'Description'
        ]

        widgets = {
            'Course' : forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Course',
                    'style':'#FF0C55',
                    'id':'Course',
                    'name':'Course',
                    
                }
            ),
            'Lecturer' : forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Lecturer',
                    'style':'#FF0C55',
                    'id':'Lecturer',
                    'name':'Lecturer',
                    
                }
            ),
            'Credit' : forms.Select(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Course',
                    'style':'#FF0C55',
                    'id':'Credit',
                    'name':'Credit',
                    
                }
            ),
            'Semester' : forms.Select(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Course',
                    'style':'#FF0C55',
                    'id':'Semester',
                    'name':'Semester',
                    
                }
            ),
            'Description' : forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Course Description',
                    'style':'#FF0C55',
                    'id':'Description',
                    'name':'Description',
                    
                }
            )
        }

main/views.py
from django.shortcuts import render


def home(request):
    page = 'HOME'
    response = {'title' : page}
    return render(request,'main/HOME1.html',response)

def about(request):
    page = 'ABOUT ME'
    response = {'title' : page}
    return render(request,'main/ABOUT ME1.html',response)

def educations(request):
    page = 'EDUCATIONS'
    response = {'title' : page}
    return render(request,'main/EDUCATIONS1.html',response)

def experiences(request):
    page = 'EXPERIENCES'
    response = {'title' : page}
    return render(request,'main/EXPERIENCES1.html',response)

def project(request):
    page = 'PROJECT'
    response = {'title' : page}
    return render(request,'main/PROJECT1.html',response)

def story1(request):
    page = 'STORY1'
    response = {'title' : page}
    return render(request,'main/Biodata.html',response)

def contact(request):
    page = 'CONTACT'
    response = {'title' : page}
    return render(request,'main/CONTACT1.html',response)

story5/views.py
from django.shortcuts import render,redirect
from .forms import CourseForm
from .models import PostCourse
from django.views.generic import ListView,DetailView,CreateView,DeleteView

# Create your views here.
class courses(ListView):
    model = PostCourse
    template_name = 'story5s/courses.html'
    #page = 'COURSES'
    #model_course = PostCourse.objects.all()
    #model_course = model.objects.all()
    #context = {
     
     
     #  'title' : page,
      #  'course' : model_course
    #}

    #return render(request,'story5s/COURSES1.html',context)

def addcourse(request):
    model = PostCourse
    form = CourseForm(request.POST or None)

    if request.POST and form.is_valid():
        form.save()
        
    context = {
        'form' : form
        }

    return render(request,'story5s/addcourse.html',context)  


class detailcourse(DetailView):
    model = PostCourse
    template_name = 'story5s/detailcourse.html'

def deletecourse(request,delete_id):
    PostCourse.objects.filter(id=delete_id).delete()
    return redirect('story5:courses')

main/templates/main/ABOUT ME1.html
{% extends 'base.html' %}

{% load static %}

<html>



        <body class="body">

            {% block header1 %}

            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                    <a href="{% url 'main:home' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">HOME</button></a>

                    <a href="{% url 'main:about' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>

                    <a href="{% url 'main:educations' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">EDUCATIONS</button></a>

                    <a href="{% url 'main:experiences' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EXPERIENCES</button></a>

                    <a href="{% url 'main:project' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">PROJECT</button></a>

                    <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}

        {% block content %}

            <h2 class="h2">
                <div class="img">
                    <img src="{% static 'img/MINGYU7.jpg' %}" alt="mingyuimage" class="centre" id="imgaboutme"> 
                </div>
                
                <div class="shape">
                    <span id="p">
                        Hello everyone, thank you so much for visiting my page. 
                        <ul></ul>
                        I’m Kaysa Syifa Wijdan Amin. I’m 19 years old.
                        <ul></ul>
                        I study Computer Science at the University of Indonesia. 
                        <ul></ul>
                        In the future, I will post my work, my project, and my accomplishment here.
                        <ul></ul>
                        Please wait for it!!
                    </span>
                </div>
                
            </h2>

        {% endblock content %}

        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>
        
        {% endblock header3 %}
  

            </h4>
              
            </h4>
        </body>

    </html>

    

main/templates/main/CONTACT1.html
{% extends 'base.html' %}

{% load static %}

<html>
    


    <body class="body">
        
        {% block header1 %}

            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                    <a href="{% url 'main:home' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">HOME</button></a>

                    <a href="{% url 'main:about' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>

                    <a href="{% url 'main:educations' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">EDUCATIONS</button></a>

                    <a href="{% url 'main:experiences' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EXPERIENCES</button></a>

                    <a href="{% url 'main:project' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">PROJECT</button></a>

                    <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}


        {% block header3 %}
    
            <h2 class="h2contact">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                <div class="center">
                    <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                        <i class="fab fa-instagram" id="link2"></i></a>

                        <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                        <i class="fab fa-linkedin"  id="link1"></i></a>
                        
                        <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                        <i class="fas fa-envelope" id="link1"></i></a>
                        
                        <i class="fab fa-line" id="link1"></i>
                </div>
            </h2>

        {% endblock header3 %}
  

            </h3>
           

            </h3>
        </body>
    </html>

main/templates/main/EDUCATIONS1.html
{% extends 'base.html' %}

{% load static %}


<html>
   


 <body class="body">
  
    {% block header1 %}

            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                    <a href="{% url 'main:home' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">HOME</button></a>

                    <a href="{% url 'main:about' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>

                    <a href="{% url 'main:educations' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">EDUCATIONS</button></a>

                    <a href="{% url 'main:experiences' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EXPERIENCES</button></a>

                    <a href="{% url 'main:project' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">PROJECT</button></a>

                    <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}
              
    
   
    {% block content %}
        <h2>
            <table class="tableed">
                <tr>
                    <td id="tded"><font id="span">University of Indonesia</td></font>
                    <td id="tded"><font id="span">2019 - Present</td></font>
                </tr>
                <tr>
                    <td id="tded"><font id="span">86 HighSchool Jakarta</td></font>
                    <td id="tded"><font id="span">2016 - 2019</td></font>
                </tr>
                <tr>
                    <td id="tded"><font id="span">177 MiddleSchool Jakarta</td></font>
                    <td id="tded"><font id="span">2013 - 2016</td></font>
                </tr>
            </table>
        </h2>

        {% endblock content %}
        
        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>
        
        {% endblock header3 %}
  

            </h4>
        
         
            </h4>
   

    </body>
</html>

main/templates/main/EXPERIENCES1.html
{% extends 'base.html' %}

{% load static %}


<html>
  
    
 <body class="body">
    
    {% block header1 %}

            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                    <a href="{% url 'main:home' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">HOME</button></a>

                    <a href="{% url 'main:about' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>

                    <a href="{% url 'main:educations' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">EDUCATIONS</button></a>

                    <a href="{% url 'main:experiences' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EXPERIENCES</button></a>

                    <a href="{% url 'main:project' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">PROJECT</button></a>

                    <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}
    
    {% block content %}


        <h2>
            <table id="tableex" class="img">
                <tr>
                    <td id="td"> 
                        <img src="{% static 'img/perak.jpg' %}" alt="perakimage" class="centre"  id="imgex">
                        <span id="spantable"> Staff of Sponsorship </span>
                    </td>
                    <td id="td">
                        <img src="{% static 'img/compfest.jpg' %}" alt="compfestimage" class="centre" id="imgex">
                        <span id="spantable">Staff of Data Science Academy</span></td>
                </tr>

                <ul></ul>
                
                <tr>
                    <td id="td"> 
                        <img src="{% static 'img/dpm.jpg' %}" alt="dpmimage" class="centre" id="imgex" >
                        <span id="spantable">Staff of Human Resources</span></td>
                    <td id="td">
                        <img src="{% static 'img/siwakng.png' %}" alt="siwakngimage" class="centre" id="imgex" >
                        <span id="spantable">Staff of Human Resources</span></td>
                </tr>
                
            </table>

        </h2>

        
    {% endblock content %}
        
       
        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>

        {% endblock header3 %}
        
  

            </h4>

             
                
            </h4>
   </body>
   </html>

main/templates/main/HOME1.html
{% extends 'base.html' %}

{% load static %}

<html>

<body class="body">

    {% block header1 %}

            <h1 class="h1hello">HELLO,</h1>
            
            <h1 class="h1kay">I'M KAYSA</h1>
            
            <h1>
                <a href="{% url 'main:home' %}">
                <button id="buttonhomepink" type="button" class="btn btn-secondary">HOME</button></a>
                <a href="{% url 'main:about' %}">
                <button id="buttonhomeorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>
                <a href="{% url 'main:educations' %}">
                <button id="buttonhomepink2" type="button" class="btn btn-secondary">EDUCATIONS</button></a>
                <a href="{% url 'main:experiences' %}">
                <button id="buttonhomeorange2" type="button" class="btn btn-secondary">EXPERIENCES</button></a>
                <a href="{% url 'main:project' %}">
                <button id="buttonhomepink3" type="button" class="btn btn-secondary">PROJECT</button></a>
                <a href="{% url 'main:contact' %}">
                <button id="buttonhomeorange3" type="button" class="btn btn-secondary">CONTACT</button></a>
            </h1>

    {% endblock header1 %}
    
        {% block header3 %}
        
            <h2 class="h2home">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                <div class="center">
                    <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                        <i class="fab fa-instagram" id="link2"></i></a>
    
                        <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                        <i class="fab fa-linkedin"  id="link1"></i></a>
                        
                        <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                        <i class="fas fa-envelope" id="link1"></i></a>
                        
                        <i class="fab fa-line" id="link1"></i>
                </div>
            </h2>

        {% endblock header3 %}

            </h3>
             
            </h3>
        </body>
   
</html>
        

main/templates/main/PROJECT1.html
{% extends 'base.html' %}

{% load static %}

<html>


        <body class="body">

        {% block header1 %}

            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                    <a href="{% url 'main:home' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">HOME</button></a>

                    <a href="{% url 'main:about' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>

                    <a href="{% url 'main:educations' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">EDUCATIONS</button></a>

                    <a href="{% url 'main:experiences' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EXPERIENCES</button></a>

                    <a href="{% url 'main:project' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">PROJECT</button></a>

                    <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}
    
        {% block content %}

        <h2 class="h2">
            <div class="card" id="card">
                <div class="card-body">
                  <h5 class="card-title" id="font-card">STORY1</h5>
                  <p class="card-text"id="p">Let's take a look on my first website.</p>
                  <a href="{% url 'main:story1' %}" class="btn btn-secondary" id="buttonpink">LET'S GO</a>
                </div>
            
            <div class="card" id="card">
                <div class="card-body">
                    <h5 class="card-title" id="font-card">STORY2</h5>
                    <p class="card-text"id="p">My Courses</p>
                    <a href="{% url 'story5:courses' %}" class="btn btn-secondary" id="buttonpink">LET'S GO</a>
            </div>

        </h2>

        {% endblock content %}

        {% block header3 %}

        <h3 class="h3">FIND ME HERE
            <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                <div class="center">
                    <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                        <i class="fab fa-instagram" id="link2"></i></a>
    
                        <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                        <i class="fab fa-linkedin"  id="link1"></i></a>
                        
                        <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                        <i class="fas fa-envelope" id="link1"></i></a>
                        
                        <i class="fab fa-line" id="link1"></i>
                </div>
        </h3>

        {% endblock header3 %}
  

            </h4>
                
            </h4>
        </body>
</html>

story5/templates/story5s/addcourse.html
{% extends 'base.html' %}

{% load static %}

<html>


        <body class="body">

        {% block header1 %}

        <h1 class="h1">
            <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
            <ul></ul>
                <a href="{% url 'story5:courses' %}">
                <button id="buttonpink" type="button" class="btn btn-secondary">COURSES</button></a>

        </h1>
        {% endblock header1 %}
    
        {% block content %}
        <h2>
        
            <form method="POST" id='font-color'>
                {% csrf_token %}
                
                <div class="form-group">
                    {{form.as_p}}
                </div>
        
                <button type="submit" id="buttonpink" class="btn btn-default">Submit</button>
            </form>
        </h2>
            {% endblock content %}
        
       
            {% block header3 %}
    
                <h3 class="h3">FIND ME HERE
                    <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                        <div class="center">
                            <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                                <i class="fab fa-instagram" id="link2"></i></a>
            
                                <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                                <i class="fab fa-linkedin"  id="link1"></i></a>
                                
                                <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                                <i class="fas fa-envelope" id="link1"></i></a>
                                
                                <i class="fab fa-line" id="link1"></i>
                        </div>
                </h3>
    
            {% endblock header3 %}
      
    
                </h4>
    
                 
                    
                </h4>
       </body>
       </html>

story5/templates/story5s/courses.html
{% extends 'base.html' %}

{% load static %}


<html>
  
    
 <body class="body">
    
    {% block header1 %}

            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                <a href="{% url 'story5:addcourse' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">ADD COURSE</button></a>
                
                <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}
    
    {% block content %}
            <h2 id='font-color'>COURSE LIST
                {% for item in object_list %}
                <tr>
                    <th scope="row"></th>
                    <td><h1><a href="{% url 'story5:detailcourse' item.id %}"><span id='font-color'>{{item.Course}}</span></a></h1></td>
                    <td><a href="{% url 'story5:deletecourse' item.id %}"><button type="delete" id="buttonpink" class="btn btn-default">Delete Course</button></a></td>
                </tr>
                {% endfor %}
            </h2>

    {% endblock content %}
        
       
        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>

        {% endblock header3 %}
        
  

            </h4>

             
                
            </h4>
   </body>
   </html>

story5/templates/story5s/detailcourse.html
{% extends 'base.html' %}

{% load static %}

<html>


        <body class="body">

            {% block header1 %}

            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>

            </h1>

        {% endblock header1 %}
    
        {% block content %}
            <h2 id='font-color'>{{item.Course}}
                <p><span id='font-color'>Lecturer = {{item.Lecturer}}</span></p>
                <p><span id='font-color'>Course University Credit Unit = {{item.Credit}} sks</span></p>
                <p><span id='font-color'>Semester = {{item.Semester}}</span></p>
                <p><span id='font-color'>Course Description = {{item.Description}}</span></p>
            </h2>
        {% endblock content %}
        
       
            {% block header3 %}
    
                <h3 class="h3">FIND ME HERE
                    <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                        <div class="center">
                            <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                                <i class="fab fa-instagram" id="link2"></i></a>
            
                                <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                                <i class="fab fa-linkedin"  id="link1"></i></a>
                                
                                <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                                <i class="fas fa-envelope" id="link1"></i></a>
                                
                                <i class="fab fa-line" id="link1"></i>
                        </div>
                </h3>
    
            {% endblock header3 %}
      
    
                </h4>
    
                 
                    
                </h4>
       </body>
       </html>